AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create and attach a Service Control Policy (SCP) at the organization root

Parameters:
  OrganizationId:
    Type: String
    Description: The ID of your AWS Organization
  SCPName:
    Type: String
    Default: DenyEC2Actions
    Description: The name for the SCP to be created
  DenyEC2Description:
    Type: String
    Default: "Deny all EC2 actions in the organization."
    Description: A description for the SCP

Resources:
  # Create the Service Control Policy (SCP) to deny all EC2 actions
  DenyEC2Policy:
    Type: AWS::Organizations::Policy
    Properties:
      Content: 
        Fn::Sub: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "DenyEC2Actions",
                "Effect": "Deny",
                "Action": "ec2:*",
                "Resource": "*"
              }
            ]
          }
      Name: !Ref SCPName
      Description: !Ref DenyEC2Description
      Type: SERVICE_CONTROL_POLICY

  # Attach the SCP to the Organization Root
  AttachSCPToRoot:
    Type: AWS::Organizations::PolicyAttachment
    Properties: 
      PolicyId: !Ref DenyEC2Policy
      TargetId: !Ref OrganizationId

Outputs:
  SCPArn:
    Description: The ARN of the newly created SCP
    Value: !GetAtt DenyEC2Policy.Arn
